# site settings
title: Zero's
subtitle: Page
email: yhs5826@gmail.com
description: Either lead, follow or get out of the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
city: Seoul
state: Songpa-gu
country: Republic of Korea

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/zeroshin
  LinkedIn:
# 현재 fontawesome에 notion icon이 없는 관계로 실패
#  Notion: https://young-repo.notion.site/c1d80fb8f08a4e4c9292972c29219b82?pvs=4
  Youtube: 
  Google-Plus:
  Instagram:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- README.md 
